[project]
name = "agents-backend"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "sqlalchemy>=2.0",
  "openai>=1.30",
  "openai-agents>=0.0.16",
  "psycopg2-binary",
  "python-dotenv"
] 